apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: llamastsack-blueprint-for-rag
  namespace: external-systems
  description: LlamaStack blueprint for RAG
spec:
  type: service
  lifecycle: production
  owner: ${{values.owner | dump}}
  providesApis:
    - ${{values.component_id | dump}}